# Generated by Django 5.1.6 on 2025-02-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notificationid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("text", models.CharField(max_length=200)),
                ("date", models.DateTimeField(verbose_name="Notification date")),
            ],
        ),
        migrations.CreateModel(
            name="Workorder",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("description", models.CharField(max_length=200)),
                ("startdate", models.DateTimeField(verbose_name="Start date")),
                ("enddate", models.DateTimeField(verbose_name="End date")),
                ("status", models.CharField(max_length=30)),
                ("results", models.CharField(max_length=200)),
                ("priority", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("displayname", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                (
                    "notifications",
                    models.ManyToManyField(
                        related_name="notifications",
                        to="workorder_project.notification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "roleid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("rolename", models.CharField(max_length=100)),
                ("permissionlevel", models.CharField(max_length=100)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder_project.user",
                    ),
                ),
                (
                    "workorderid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder_project.workorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="workorder",
            field=models.ManyToManyField(
                related_name="workorder", to="workorder_project.workorder"
            ),
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "approvalid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder_project.user",
                    ),
                ),
                (
                    "workorderid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workorder_project.workorder",
                    ),
                ),
            ],
        ),
    ]
