# Generated by Django 5.1.6 on 2025-03-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workorder_project",
            "0002_remove_role_userid_remove_role_workorderid_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorder",
            old_name="id",
            new_name="workorderid",
        ),
    ]
