# Generated by Django 5.1.6 on 2025-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_project", "0003_rename_id_workorder_workorderid"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workorder",
            name="workorderid",
            field=models.IntegerField(unique=True),
        ),
    ]
