# Generated by Django 5.1.6 on 2025-03-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_project", "0004_workorder_id_alter_workorder_workorderid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="id",
        ),
        migrations.AlterField(
            model_name="workorder",
            name="workorderid",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
