# Generated by Django 5.1.6 on 2025-03-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_project", "0005_remove_workorder_id_alter_workorder_workorderid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="role",
        ),
        migrations.AddField(
            model_name="notification",
            name="roles",
            field=models.ManyToManyField(
                related_name="roles", to="workorder_project.role"
            ),
        ),
    ]
