# Generated by Django 5.1.6 on 2025-03-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder_project", "0006_remove_notification_role_notification_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="workorder",
            new_name="workorderid",
        ),
    ]
